name: 'Push2SharePoint'
description: 'Upload a file to a SharePoint document library'
author: 'sjultra inc.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  username:
    description: 'SharePoint account username'
    required: true
  password:
    description: 'SharePoint account password'
    required: true
  file_name:
    description: 'The name of the file to upload'
    required: true
  full_url:
    description: 'The full URL of the SharePoint site'
    required: true
  target_subfolder:
    description: 'The subfolder in the document library where the file should be uploaded'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout reusable action repository
      uses: actions/checkout@v2
      with:
        repository: 'sjultra/Push2Sharepoint' # Replace with the reusable action's owner and repo name
        ref: 'v1.0.12' # Replace with the desired branch, commit, or tag
        path: './action'
        
    - name: Install Office365-REST-Python-Client
      run: pip install Office365-REST-Python-Client==2.2.0
      shell: bash
      
    - name: Check package version
      run: pip show Office365-REST-Python-Client
      shell: bash
      
    - name: List files in repository
      run: ls -R
      shell: bash

    - name: Run script
      run: python action/Push2Sharepoint.py --username ${{ env.USERNAME }} --password ${{ env.PASSWORD }} --site_url ${{ env.FULL_URL }} --folder_name ${{ env.TARGET_SUBFOLDER }} --documents ${{ env.FILE_NAME }}
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        FULL_URL: ${{ inputs.full_url }}
        TARGET_SUBFOLDER: ${{ inputs.target_subfolder }}
        FILE_NAME: ${{ inputs.file_name }}
