name: 'Push2SharePoint'
description: 'Upload a file to a SharePoint document library'
author: 'sjultra inc.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  username:
    description: 'SharePoint account username'
    required: true
  password:
    description: 'SharePoint account password'
    required: true
  file_name:
    description: 'The name of the file to upload'
    required: true
  full_url:
    description: 'The full URL of the SharePoint site'
    required: true
  target_subfolder:
    description: 'The subfolder in the document library where the file should be uploaded'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: './action'
    - run: pip install Office365-REST-Python-Client
      shell: bash
      
    - name: List files in repository
      run: ls -R
      shell: bash

    - run: python action/upload_to_sharepoint.py ${{ inputs.username }} ${{ inputs.password }} ${{ inputs.file_name }} ${{ inputs.full_url }} ${{ inputs.target_subfolder }}
      shell: bash
